# This file was generated by GoReleaser. DO NOT EDIT.
cask "semtag" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "754b299c607cce1fbfc798add68257746c3749a31273d35a690936b9935f1a28"
      url "https://github.com/dev-shimada/semtag/releases/download/v#{version}/semtag_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2a6a69d91d81740bedb457dc259f207a2b2619b6c6f8c0465c26ff6437ff6bee"
      url "https://github.com/dev-shimada/semtag/releases/download/v#{version}/semtag_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8de67a7637ca727c75243bceef290fe13425b492377cab928b3bf02f5feea5b0"
      url "https://github.com/dev-shimada/semtag/releases/download/v#{version}/semtag_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7f0a4b0f8dd489d0e3e53f5d699daee3d7590249786d8a58af75a0aa9a738e31"
      url "https://github.com/dev-shimada/semtag/releases/download/v#{version}/semtag_Linux_arm64.tar.gz"
    end
  end

  name "semtag"
  desc "A CLI tool to interactively create and manage semver git tags"
  homepage "https://github.com/dev-shimada/semtag"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semtag"

  # No zap stanza required

end
