# This file was generated by GoReleaser. DO NOT EDIT.
cask "semtag" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "022a4e1e765a706555ec002151fe7f00d37e859c202663f46a7225295ecab43c"
      url "https://github.com/dev-shimada/semtag/releases/download/v#{version}/semtag_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f24680e9745386c7168b632ba1bcabc0bf145ab23926b454b4ad263853e3dcb0"
      url "https://github.com/dev-shimada/semtag/releases/download/v#{version}/semtag_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "12fd40eac26ac962029ab41e1f8d47f6ddf0e0ab793dd0c4f6b41c27b157c86c"
      url "https://github.com/dev-shimada/semtag/releases/download/v#{version}/semtag_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e72942f66d5d7416360ccee5db9652a1b38ad7339a215ab489b2710693764d98"
      url "https://github.com/dev-shimada/semtag/releases/download/v#{version}/semtag_Linux_arm64.tar.gz"
    end
  end

  name "semtag"
  desc "A CLI tool to interactively create and manage semver git tags"
  homepage "https://github.com/dev-shimada/semtag"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "semtag"

  # No zap stanza required

end
